name: prog2 pipeline

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version to release (e.g. 1.0.0)'
        required: true
      development-version:
        description: 'Next snapshot version (e.g. 1.0.1-SNAPSHOT)'
        required: true

permissions:
  contents: write

jobs:
  build-develop:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build & Test
        run: mvn clean verify

  release:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Run Maven Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn release:prepare -B \
            -DreleaseVersion=${{ github.event.inputs.release-version }} \
            -DdevelopmentVersion=${{ github.event.inputs.development-version }} \
            -DpushChanges=true
          mvn release:perform -B

      - name: Merge develop → main
        run: |
          git checkout main
          git pull origin main
          git merge origin/develop
          git push origin main
